language: ruby
sudo: false
rvm:
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.4.0
  - 2.4.1
  - ruby-head
  - jruby-9.1.12.0
before_install:
- gem install bundler --no-document -v '~> 1.13.3'
before_script:
  - unset JRUBY_OPTS
script: bundle exec rspec spec
env:
  global:
    - JRUBY_OPTS='--debug'
