dist: trusty
sudo: false
language: ruby
cache: bundler

rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.2
  - ruby-head
  - jruby-9.2.0.0

env:
  global:
    - JRUBY_OPTS='--debug'

before_install:
  - gem install bundler
  - gem update --system

script: bundle exec rspec
