services:
  - docker

dist: trusty
sudo: false
cache: bundler

git:
  depth: false

test: &test
  stage: Test
  language: ruby
  before_install:
    - yes | gem update --system
  script: bundle exec rspec

jobs:
  include:
    - <<: *test
      rvm: 2.6.5
    - <<: *test
      rvm: 2.5.7

    - stage: coditsu
      language: ruby
      rvm: 2.6.5
      before_install:
        - yes | gem update --system
      script: \curl -sSL https://api.coditsu.io/run/ci | bash

stages:
  - test
  - coditsu
