language: ruby
sudo: false
rvm:
  - 2.3.0
  - 2.3.1
  - 2.3.2
  - 2.3.3
  - 2.3.4
  - 2.4.0
  - 2.4.1
  - 2.4.2
  - 2.5.0
  - jruby-head
script: bundle exec rspec spec/
env:
  global:
    - JRUBY_OPTS='--debug'
install: bundle install --jobs=3 --retry=3
