services:
  - docker

dist: trusty
sudo: false
cache: bundler

git:
  depth: false

test: &test
  stage: Test
  language: ruby
  before_install:
    - gem install bundler
    - gem update --system
  script: bundle exec rspec

jobs:
  include:
    - <<: *test
      rvm: 2.6.3
    - <<: *test
      rvm: 2.5.5

    - stage: coditsu
      language: ruby
      rvm: 2.6.3
      before_install:
        - gem update --system
        - gem install bundler
      script: \curl -sSL https://api.coditsu.io/run/ci | bash

stages:
  - coditsu
  - test
