name: Verify Action Pins
on:
  pull_request:
    paths:
      - '.github/workflows/**'
jobs:
  verify_action_pins:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1
      - name: Check SHA pins
        run: |
          if grep -E -r "uses: .*/.*@(v[0-9]+|main|master)($|[[:space:]]|$)" --include="*.yml" --include="*.yaml" .github/workflows/ | grep -v "#"; then
            echo "::error::Actions should use SHA pins, not tags or branch names"
            exit 1
          fi
